/**
 * Turkish keyword index for the curated emoji set in add-addiction's
 * picker. Used by the search bar to filter across all six categories
 * at once; does NOT extend the picker — every glyph here also lives
 * in EMOJI_CATEGORIES.
 *
 * Conventions:
 *   - All keywords are lowercase, no diacritic stripping (we lowercase
 *     the user query the same way before comparing).
 *   - Each entry has at least one Turkish word AND one English word —
 *     a Turkish user typing "smoke" should still find 🚬, and a Turkish
 *     user typing "duman" should also find it.
 *   - Synonyms welcome ("alkol" + "icki" + "drink"); avoid sentence-y
 *     phrases.
 */
export const EMOJI_KEYWORDS: Record<string, string[]> = {
  // Substances
  '🚬': ['sigara', 'duman', 'tutun', 'cigarette', 'smoke'],
  '🚭': ['sigara yok', 'no smoking', 'yasak'],
  '💨': ['duman', 'nefes', 'wind', 'breath', 'smoke'],
  '🌿': ['ot', 'yesil', 'bitki', 'weed', 'herb'],
  '🍃': ['yaprak', 'leaf', 'green'],
  '🍺': ['bira', 'beer', 'icki'],
  '🍻': ['bira', 'kadeh', 'cheers', 'beer'],
  '🍷': ['sarap', 'wine', 'kadeh', 'icki'],
  '🥂': ['sampanya', 'champagne', 'kadeh', 'kutla'],
  '🍾': ['sampanya', 'sise', 'champagne', 'celebrate'],
  '🍸': ['kokteyl', 'cocktail', 'martini', 'icki'],
  '🍹': ['kokteyl', 'tropical', 'cocktail'],
  '🍶': ['sake', 'icki', 'sake'],
  '🥃': ['viski', 'whiskey', 'icki', 'whisky'],
  '🧉': ['mate', 'mate'],
  '☕': ['kahve', 'coffee', 'cay'],
  '🍵': ['cay', 'tea', 'matcha'],
  '🥤': ['icecek', 'soda', 'drink', 'kola', 'cola'],
  '🧋': ['boba', 'bubble tea', 'tapioca'],
  '🧃': ['meyve suyu', 'kutu', 'juice'],
  '💊': ['hap', 'ilac', 'pill', 'medicine'],
  '💉': ['igne', 'enjeksiyon', 'syringe', 'shot'],
  '🧪': ['tup', 'lab', 'tube', 'kimya'],
  '⚗️': ['imbik', 'kimya', 'alembic', 'distill'],
  '🩸': ['kan', 'blood'],
  // Food
  '🍔': ['burger', 'hamburger'],
  '🍟': ['patates', 'fries', 'kizartma'],
  '🌭': ['sosisli', 'hotdog', 'sosis'],
  '🍕': ['pizza', 'pizza'],
  '🌮': ['taco', 'tako'],
  '🌯': ['burrito', 'durum'],
  '🥙': ['durum', 'pita', 'kebap'],
  '🥪': ['sandvic', 'sandwich'],
  '🥨': ['simit', 'pretzel'],
  '🍿': ['patlamis misir', 'popcorn'],
  '🍩': ['donut', 'tatli'],
  '🍪': ['kurabiye', 'cookie', 'biscuit'],
  '🧁': ['cupcake', 'kek'],
  '🍰': ['pasta', 'cake', 'kek'],
  '🎂': ['dogum gunu', 'birthday', 'pasta'],
  '🥧': ['pay', 'pie', 'tart'],
  '🍫': ['cikolata', 'chocolate'],
  '🍬': ['seker', 'candy', 'sweet'],
  '🍭': ['lolipop', 'lollipop', 'seker'],
  '🍮': ['puding', 'pudding', 'flan'],
  '🍦': ['dondurma', 'icecream', 'ice cream'],
  '🍨': ['dondurma', 'kase', 'ice cream'],
  '🍯': ['bal', 'honey'],
  '🥞': ['krep', 'pancake', 'pankek'],
  '🧇': ['waffle', 'wafle'],
  // Activities
  '📱': ['telefon', 'phone', 'feed', 'sosyal medya', 'instagram'],
  '💻': ['laptop', 'bilgisayar', 'computer'],
  '🖥️': ['monitor', 'desktop', 'ekran'],
  '⌨️': ['klavye', 'keyboard'],
  '🖱️': ['mouse', 'fare'],
  '🎮': ['oyun', 'game', 'gaming', 'controller'],
  '🕹️': ['joystick', 'oyun', 'arcade'],
  '🎲': ['zar', 'dice', 'sans'],
  '🎰': ['kumar', 'slot', 'jackpot', 'casino', 'bahis'],
  '🎴': ['kart', 'card', 'iskambil'],
  '🃏': ['joker', 'kart', 'card', 'iskambil'],
  '♠️': ['maca', 'spade', 'kart'],
  '♥️': ['kupa', 'heart', 'kart'],
  '♦️': ['karo', 'diamond', 'kart'],
  '♣️': ['sinek', 'club', 'kart'],
  '📺': ['televizyon', 'tv'],
  '🎬': ['film', 'movie', 'klaket'],
  '📷': ['fotograf', 'kamera', 'camera'],
  '🎵': ['muzik', 'music', 'nota'],
  '🎧': ['kulaklik', 'headphones', 'muzik'],
  '🛍️': ['alisveris', 'shopping', 'canta'],
  '💸': ['para', 'money', 'harcama', 'spending'],
  '💳': ['kredi karti', 'card', 'payment', 'odeme'],
  '💰': ['para', 'money', 'cash', 'kese'],
  // Faces (mood)
  '🙈': ['goz kapali', 'utanc', 'see no evil', 'shame'],
  '🙉': ['kulak kapali', 'hear no evil'],
  '🙊': ['sus', 'speak no evil', 'sessizlik'],
  '😶': ['sessiz', 'speechless', 'agiz yok'],
  '😔': ['uzgun', 'pensive', 'sad'],
  '😞': ['hayal kirikligi', 'disappointed', 'uzgun'],
  '😟': ['endiseli', 'worried', 'kaygili'],
  '😣': ['acili', 'persevering', 'sikinti'],
  '😖': ['sikinti', 'confounded', 'iz cekme'],
  '😩': ['bitkin', 'weary', 'yorgun'],
  '😫': ['yorgun', 'tired', 'exhausted'],
  '😤': ['ofkeli', 'huff', 'kizgin', 'ofke'],
  '😡': ['kizgin', 'angry', 'red'],
  '😠': ['kizgin', 'angry'],
  '🤬': ['kufur', 'cursing', 'ofke'],
  '😢': ['aglama', 'crying', 'gozyasi'],
  '😭': ['aglama', 'sobbing', 'cok aglama'],
  '😪': ['uykulu', 'sleepy', 'salya'],
  '😴': ['uyuyor', 'sleeping'],
  '🥱': ['esneme', 'yawn', 'yorgun'],
  '🥺': ['yalvaran', 'pleading', 'kucuk gozler'],
  '😬': ['gergin', 'grimacing', 'sirip'],
  '🫠': ['eriyik', 'melting', 'eriyen'],
  '🫣': ['kasilmis', 'peeking', 'utanc'],
  '🫨': ['titreyen', 'shaking', 'sok'],
  '🤤': ['salya', 'drooling', 'imrenme', 'craving'],
  '😋': ['lezzetli', 'yummy', 'tatli'],
  '🥹': ['gozyasi tutuyor', 'holding back tears'],
  '👁️': ['goz', 'eye', 'bakma'],
  '🫥': ['kayip', 'dotted line', 'gizli', 'invisible'],
  // Symbols
  '⚡': ['simsek', 'lightning', 'enerji', 'electric'],
  '🔥': ['ates', 'fire', 'sicak', 'yangin'],
  '💥': ['patlama', 'explosion', 'boom'],
  '💢': ['ofke', 'anger', 'damar'],
  '💫': ['yildiz', 'dizzy', 'donme'],
  '✨': ['parlak', 'sparkle', 'pirilti'],
  '💯': ['yuz', 'hundred', '100', 'tam'],
  '❤️': ['kalp', 'heart', 'kirmizi', 'sevgi'],
  '🖤': ['siyah kalp', 'black heart', 'karanlik'],
  '💔': ['kirik kalp', 'broken heart'],
  '🩷': ['pembe kalp', 'pink heart'],
  '❤️‍🩹': ['iyilesen kalp', 'mending heart', 'yara'],
  '⏰': ['saat', 'alarm', 'time'],
  '⏳': ['kum saati', 'hourglass', 'sure'],
  '🕯️': ['mum', 'candle', 'isik'],
  '🧠': ['beyin', 'brain', 'akil'],
  '👁️‍🗨️': ['goz konusan', 'eye in speech'],
  '🔞': ['18+', 'no minors', 'yas siniri'],
  '⚠️': ['uyari', 'warning', 'tehlike'],
  '🚫': ['yasak', 'no entry', 'prohibited'],
  '⛔': ['durr', 'no entry', 'yasak'],
  '🆘': ['sos', 'sos', 'yardim', 'help'],
  // Objects
  '🎁': ['hediye', 'gift', 'paket'],
  '🎀': ['kurdele', 'ribbon', 'bow'],
  '🛒': ['sepet', 'cart', 'alisveris'],
  '👛': ['cuzdan', 'purse', 'kese'],
  '💼': ['canta', 'briefcase', 'is'],
  '🔑': ['anahtar', 'key'],
  '🗝️': ['eski anahtar', 'old key'],
  '📦': ['kutu', 'package', 'box'],
  '🧴': ['sise', 'lotion', 'losyon'],
  '🧻': ['tuvalet kagidi', 'toilet paper'],
  '🪞': ['ayna', 'mirror'],
  '🛏️': ['yatak', 'bed'],
  '🚿': ['dus', 'shower'],
  '🪙': ['madeni para', 'coin'],
  '💎': ['elmas', 'diamond', 'mucevher'],
  '⌚': ['saat', 'watch', 'kol saati'],
  '📿': ['tespih', 'beads', 'rosary'],
  '👠': ['topuklu', 'high heel', 'ayakkabi'],
  '👗': ['elbise', 'dress', 'kiyafet'],
  '💄': ['ruj', 'lipstick', 'makyaj'],
  '💋': ['opucuk', 'kiss'],
  '💅': ['oje', 'nail polish', 'manikur'],
  '🎯': ['hedef', 'target', 'dart'],
  '🎪': ['cadir', 'circus', 'sirk'],
};

/**
 * Match an emoji against a search query. Empty query matches everything.
 * Lowercases both sides; substring match (so "kah" finds 🍔🍯☕).
 */
export function emojiMatchesQuery(emoji: string, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (q.length === 0) return true;
  const keywords = EMOJI_KEYWORDS[emoji];
  if (!keywords) return false;
  return keywords.some((k) => k.includes(q));
}
